update to snowpack 3.1.0-pre.11 results in
Unhandled Runtime Error
SyntaxError: import not found: forEach
Source
http://localhost:8080/_snowpack/pkg/yup.v0.32.9.js [:4:17]